/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import domen.Izvestaj;
import domen.Lekar;
import domen.ZakazanTermin;
import java.awt.Font;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import kontr.Kontroler;
import kontr.PdfGenerator;

/**
 *
 * @author Nemanja
 */
public class FormaPrikazIzvestaja extends javax.swing.JFrame {

    private AutocompleteTextField tfPacijent;
    private Izvestaj i;
    private boolean zakazan = true;

    /**
     * Creates new form FormaJedanIzvestaj
     */
    public FormaPrikazIzvestaja(Izvestaj i) {
        initComponents();
        this.i = i;
        popuniComboLekari();
        if (i.getZt() != null) {
            DateTimeFormatter f = DateTimeFormatter.ofPattern("dd.MM.yyyy");
            lblDatum.setText(lblDatum.getText() + " " + i.getZt().getDatumVreme().toLocalDate().format(f));
            lblPac1.setText(lblPac1.getText()+i.getZt().getPac());
            cmbLekari1.setSelectedItem(i.getZt().getLekar());
            if (i.getAnamneza() != null) {
                taAnamneza.setText(i.getAnamneza());
                taDijagnoza.setText(i.getDg());
                taTerapija.setText(i.getTerapija());
                btnDodaj.setVisible(false);
                taAnamneza.setEditable(false);
                taDijagnoza.setEditable(false);
                taTerapija.setEditable(false);
            }
            panelPacijent.setVisible(false);
        } else {
            tfPacijent = new AutocompleteTextField(Kontroler.getInstance().vratiPacijente(), 20);
            tfPacijent.setFont(new Font("Arial", Font.PLAIN, 20));
            panelPacijent.setLayout(new java.awt.BorderLayout());
            panelPacijent.add(tfPacijent, java.awt.BorderLayout.CENTER);
            panelPacijent.revalidate();
            panelPacijent.repaint();
            zakazan=false;
            lblDatum.setVisible(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLekar = new javax.swing.JLabel();
        lblDatum = new javax.swing.JLabel();
        lblPac1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAnamneza = new javax.swing.JTextArea();
        lblDatum1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taDijagnoza = new javax.swing.JTextArea();
        lblDatum2 = new javax.swing.JLabel();
        lblDatum3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taTerapija = new javax.swing.JTextArea();
        btnDodaj = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbLekari1 = new javax.swing.JComboBox<>();
        panelPacijent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1250, 681));

        lblLekar.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        lblLekar.setText("Lekar:");

        lblDatum.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        lblDatum.setText("Datum pregleda:");

        lblPac1.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        lblPac1.setText("Pacijent:");

        taAnamneza.setColumns(20);
        taAnamneza.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        taAnamneza.setLineWrap(true);
        taAnamneza.setRows(5);
        taAnamneza.setWrapStyleWord(true);
        jScrollPane1.setViewportView(taAnamneza);

        lblDatum1.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        lblDatum1.setText("Anamneza:");

        taDijagnoza.setColumns(20);
        taDijagnoza.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        taDijagnoza.setLineWrap(true);
        taDijagnoza.setRows(5);
        taDijagnoza.setWrapStyleWord(true);
        jScrollPane2.setViewportView(taDijagnoza);

        lblDatum2.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        lblDatum2.setText("Dijagnoza:");

        lblDatum3.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        lblDatum3.setText("Terapija:");

        taTerapija.setColumns(20);
        taTerapija.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        taTerapija.setLineWrap(true);
        taTerapija.setRows(5);
        taTerapija.setWrapStyleWord(true);
        jScrollPane3.setViewportView(taTerapija);

        btnDodaj.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnDodaj.setText("Dodaj izvestaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        cmbLekari1.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N

        javax.swing.GroupLayout panelPacijentLayout = new javax.swing.GroupLayout(panelPacijent);
        panelPacijent.setLayout(panelPacijentLayout);
        panelPacijentLayout.setHorizontalGroup(
            panelPacijentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
        );
        panelPacijentLayout.setVerticalGroup(
            panelPacijentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblLekar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbLekari1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3379, 3379, 3379)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(226, 226, 226)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panelPacijent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblPac1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(63, 63, 63)
                                        .addComponent(btnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(35, 35, 35))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDatum1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(69, 69, 69)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDatum2, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDatum3, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblLekar)
                                .addComponent(cmbLekari1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnDodaj))
                        .addGap(34, 34, 34)
                        .addComponent(lblDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPac1)
                        .addGap(18, 18, 18)
                        .addComponent(panelPacijent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDatum1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDatum2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(lblDatum3)
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1371, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        if(zakazan==false){
            ZakazanTermin zt = new ZakazanTermin(tfPacijent.getSelectedPacijent(), 
                    LocalDateTime.now(), (Lekar) cmbLekari1.getSelectedItem());
            i.setZt(zt);
            Kontroler.getInstance().dodajZakazanT(zt);
        }
        i.setAnamneza(taAnamneza.getText());
        i.setDg(taDijagnoza.getText());
        i.setTerapija(taTerapija.getText());
        Kontroler.getInstance().dodajIzvestaj(i);
        PdfGenerator.exportIzvestaj(i);
        this.dispose();
    }//GEN-LAST:event_btnDodajActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JComboBox<Lekar> cmbLekari1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblDatum;
    private javax.swing.JLabel lblDatum1;
    private javax.swing.JLabel lblDatum2;
    private javax.swing.JLabel lblDatum3;
    private javax.swing.JLabel lblLekar;
    private javax.swing.JLabel lblPac1;
    private javax.swing.JPanel panelPacijent;
    private javax.swing.JTextArea taAnamneza;
    private javax.swing.JTextArea taDijagnoza;
    private javax.swing.JTextArea taTerapija;
    // End of variables declaration//GEN-END:variables
        private void popuniComboLekari() {
        List<Lekar> ls = Kontroler.getInstance().vratiLekare();
        for (Lekar l : ls) {
            cmbLekari1.addItem(l);
        }
    }
}
