/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import domen.DostupanTermin;
import domen.Izvestaj;
import domen.ZakazanTermin;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import kontr.Kontroler;

/**
 *
 * @author Nemanja
 */
public class FormaTermini extends javax.swing.JFrame {

    private ModelTabeleDostupniTermini mtd;
    private ModelTabeleZakazaniTermini mtz;

    /**
     * Creates new form FormaDostupni
     */
    public FormaTermini() {
        initComponents();
        mtd = new ModelTabeleDostupniTermini(Kontroler.getInstance().vratiDostupneT());
        mtz = new ModelTabeleZakazaniTermini(Kontroler.getInstance().vratiZakazaneT());
        tblDostupni.setModel(mtd);
        tblZakazani.setModel(mtz);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dtcDatumPregleda = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblZakazani = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDostupni = new javax.swing.JTable();
        btnFilter = new javax.swing.JButton();
        btnDodaj = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        btnZakazi = new javax.swing.JButton();
        btnObrisiZakazan = new javax.swing.JButton();
        btnIzvestaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 30)); // NOI18N
        jLabel1.setText("Dostupni termini");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 30)); // NOI18N
        jLabel2.setText("Zakazani termini");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Datum:");

        dtcDatumPregleda.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        tblZakazani.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblZakazani.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblZakazani.setRowHeight(25);
        jScrollPane1.setViewportView(tblZakazani);

        tblDostupni.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblDostupni.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDostupni.setRowHeight(25);
        jScrollPane2.setViewportView(tblDostupni);

        btnFilter.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnFilter.setText("Pretraga po datumu");
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });

        btnDodaj.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnDodaj.setText("Dodaj dostupni termin");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnObrisi.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnObrisi.setText("Obriši dostupni termin");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnZakazi.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnZakazi.setText("Zakaži termin");
        btnZakazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZakaziActionPerformed(evt);
            }
        });

        btnObrisiZakazan.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnObrisiZakazan.setText("Otkaži zakazan termin");
        btnObrisiZakazan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiZakazanActionPerformed(evt);
            }
        });

        btnIzvestaj.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnIzvestaj.setText("Dodaj izveštaj");
        btnIzvestaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzvestajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtcDatumPregleda, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnIzvestaj, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(btnObrisiZakazan, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(btnObrisi))
                                    .addComponent(btnZakazi, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(131, 131, 131)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                        .addComponent(dtcDatumPregleda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnFilter))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDodaj)
                            .addComponent(btnObrisi)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnObrisiZakazan)
                            .addComponent(btnIzvestaj))))
                .addGap(21, 21, 21)
                .addComponent(btnZakazi)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        DijalogDostupanT ddt = new DijalogDostupanT(this, rootPaneCheckingEnabled);
        ddt.setVisible(true);
        osveziTabelu();
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        DostupanTermin dt = mtd.getTermin(tblDostupni.getSelectedRow());
        Kontroler.getInstance().izbrisiDostupniT(dt);
        osveziTabelu();
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
        Date d = dtcDatumPregleda.getDate();
        System.out.println(d);
        LocalDate ld = d.toInstant().atZone(ZoneId.of("Europe/Belgrade")).toLocalDate();
        if (ZoneId.systemDefault().getId().equals("Asia/Bangkok")) {
            ld = ld.plusDays(1);
        }
        System.out.println(ld);
        mtd = new ModelTabeleDostupniTermini(Kontroler.getInstance().filtrirajTermine(ld));
        tblDostupni.setModel(mtd);
        mtz = new ModelTabeleZakazaniTermini(Kontroler.getInstance().filtrirajZakazaneT(ld));
        tblZakazani.setModel(mtz);
    }//GEN-LAST:event_btnFilterActionPerformed

    private void btnZakaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZakaziActionPerformed
        DostupanTermin dt = mtd.getTermin(tblDostupni.getSelectedRow());
        DijalogZakazivanje dzak = new DijalogZakazivanje(this, rootPaneCheckingEnabled,dt);
        dzak.setVisible(true);
        osveziTabelu();
    }//GEN-LAST:event_btnZakaziActionPerformed

    private void btnObrisiZakazanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiZakazanActionPerformed
        ZakazanTermin zt = mtz.getTermin(tblZakazani.getSelectedRow());
        Kontroler.getInstance().dodajDostupanT(new DostupanTermin(zt.getDatumVreme(),zt.getLekar()));
        Kontroler.getInstance().izbrisiZakazanT(zt);
        osveziTabelu();
    }//GEN-LAST:event_btnObrisiZakazanActionPerformed

    private void btnIzvestajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzvestajActionPerformed
        ZakazanTermin zt = mtz.getTermin(tblZakazani.getSelectedRow());
        Izvestaj i = new Izvestaj(zt, null,null,null);
        FormaPrikazIzvestaja fpi = new FormaPrikazIzvestaja(i);
        fpi.setVisible(true);
    }//GEN-LAST:event_btnIzvestajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaTermini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaTermini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaTermini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaTermini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaTermini().setVisible(true);
            }
        });
    }

    private void osveziTabelu() {
        mtd = new ModelTabeleDostupniTermini(Kontroler.getInstance().vratiDostupneT());
        mtz = new ModelTabeleZakazaniTermini(Kontroler.getInstance().vratiZakazaneT());
        tblDostupni.setModel(mtd);
        tblZakazani.setModel(mtz);
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnIzvestaj;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnObrisiZakazan;
    private javax.swing.JButton btnZakazi;
    private com.toedter.calendar.JDateChooser dtcDatumPregleda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDostupni;
    private javax.swing.JTable tblZakazani;
    // End of variables declaration//GEN-END:variables
}
